// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQYpj4GOfYpgA5hjbbtaFKwOC_oSPkOMo',
    appId: '1:445821735295:web:20c988de6916d102304a4a',
    messagingSenderId: '445821735295',
    projectId: 'a-plus-foods',
    authDomain: 'a-plus-foods.firebaseapp.com',
    storageBucket: 'a-plus-foods.appspot.com',
    measurementId: 'G-BJ1SV5JZHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVuUGr7_NlirlodBH255phl4hTy7Iohr8',
    appId: '1:445821735295:android:817cf94bc9748c41304a4a',
    messagingSenderId: '445821735295',
    projectId: 'a-plus-foods',
    storageBucket: 'a-plus-foods.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8gR1rxHpPBUPj-FYlC5f6Ww75O-UGETw',
    appId: '1:445821735295:ios:e72d90ae66bdd0ba304a4a',
    messagingSenderId: '445821735295',
    projectId: 'a-plus-foods',
    storageBucket: 'a-plus-foods.appspot.com',
    iosClientId: '445821735295-cpc42koo2smip11r5ejsokhhm7prps82.apps.googleusercontent.com',
    iosBundleId: 'com.example.aPlusFoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8gR1rxHpPBUPj-FYlC5f6Ww75O-UGETw',
    appId: '1:445821735295:ios:e72d90ae66bdd0ba304a4a',
    messagingSenderId: '445821735295',
    projectId: 'a-plus-foods',
    storageBucket: 'a-plus-foods.appspot.com',
    iosClientId: '445821735295-cpc42koo2smip11r5ejsokhhm7prps82.apps.googleusercontent.com',
    iosBundleId: 'com.example.aPlusFoods',
  );
}
